/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.pruebas.gestionbiblioteca;

import dtos.DevolucionDTO;
import dtos.LibroDTO;
import dtos.PrestamoDTO;
import dtos.UsuarioDTO;
import fachada.FachadaGestionBiblioteca;
import fachada.TipoAccion;
import fachada.TipoBusqueda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisa M
 */
public class PanelDashboard extends javax.swing.JPanel {
    private FachadaGestionBiblioteca gestor;
    private static List<UsuarioDTO> usuarios;
    private static List<LibroDTO> libros;
    private static List<PrestamoDTO> prestamos;
    
    private LibroDTO libroSeleccionado;
    private static PrestamoDTO prestamoSeleccionado;
    private UsuarioDTO usuarioSeleccionado;
    
    private static DefaultTableModel modeloTablaUsuarios;
    private static DefaultTableModel modeloTablaPrestamos;
    private static DefaultTableModel modeloTablaLibros;
    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard(FachadaGestionBiblioteca gestor) {
        initComponents();
        this.gestor = gestor;
        mostrarUsuarios();
        buscarLibros();
        mostrarLibros();
        buscarPrestamos();
        mostrarPrestamos();
        btnDev.setVisible(false);
        btnRemoverLibro.setVisible(false);
        btnRemoverUsuario.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab1 = new javax.swing.JTabbedPane();
        panelLibros = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        filtros = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        btnAggLibro = new javax.swing.JButton();
        btnRemoverLibro = new javax.swing.JButton();
        panelPrestamos = new javax.swing.JPanel();
        btnRegistrarPrestamo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPrestamos = new javax.swing.JTable();
        btnDev = new javax.swing.JButton();
        panelUsuarios = new javax.swing.JPanel();
        btnAgregarUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnRemoverUsuario = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("Sistema Gestion de Biblioteca");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tab1.setBackground(new java.awt.Color(102, 255, 102));
        tab1.setForeground(new java.awt.Color(51, 51, 51));
        tab1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        panelLibros.setBackground(new java.awt.Color(153, 153, 153));
        panelLibros.setMaximumSize(new java.awt.Dimension(650, 400));
        panelLibros.setMinimumSize(new java.awt.Dimension(650, 400));
        panelLibros.setPreferredSize(new java.awt.Dimension(650, 400));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar libro");
        btnBuscar.setMaximumSize(new java.awt.Dimension(115, 38));
        btnBuscar.setMinimumSize(new java.awt.Dimension(115, 38));
        btnBuscar.setPreferredSize(new java.awt.Dimension(115, 38));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });

        filtros.setBackground(new java.awt.Color(204, 204, 204));
        filtros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filtros.setForeground(new java.awt.Color(0, 0, 0));
        filtros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "titulo", "autor", "isbn" }));

        tablaLibros.setBackground(new java.awt.Color(255, 255, 255));
        tablaLibros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Titulo", "Autor", "ISBN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaLibros);

        btnAggLibro.setBackground(new java.awt.Color(0, 153, 0));
        btnAggLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAggLibro.setText("Agregar libro");
        btnAggLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggLibroActionPerformed(evt);
            }
        });

        btnRemoverLibro.setBackground(new java.awt.Color(51, 51, 51));
        btnRemoverLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoverLibro.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverLibro.setText("Remover libro");
        btnRemoverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibrosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addComponent(btnAggLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnRemoverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLibrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAggLibro, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnRemoverLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        tab1.addTab("Libros", panelLibros);

        panelPrestamos.setBackground(new java.awt.Color(153, 153, 153));

        btnRegistrarPrestamo.setBackground(new java.awt.Color(0, 153, 0));
        btnRegistrarPrestamo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarPrestamo.setText("Registrar prestamo");
        btnRegistrarPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPrestamoActionPerformed(evt);
            }
        });

        tablaPrestamos.setBackground(new java.awt.Color(255, 255, 255));
        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Usuario", "Libro", "Fecha prestamo", "Fecha limite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaPrestamos);

        btnDev.setBackground(new java.awt.Color(0, 153, 0));
        btnDev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDev.setText("Devolver libro");
        btnDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrestamosLayout = new javax.swing.GroupLayout(panelPrestamos);
        panelPrestamos.setLayout(panelPrestamosLayout);
        panelPrestamosLayout.setHorizontalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrestamosLayout.createSequentialGroup()
                        .addComponent(btnRegistrarPrestamo)
                        .addGap(27, 27, 27)
                        .addComponent(btnDev, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelPrestamosLayout.setVerticalGroup(
            panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrestamosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDev, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        tab1.addTab("Prestamos", panelPrestamos);

        panelUsuarios.setBackground(new java.awt.Color(153, 153, 153));

        btnAgregarUser.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregarUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarUser.setText("Agregar usuario");
        btnAgregarUser.setMaximumSize(new java.awt.Dimension(132, 28));
        btnAgregarUser.setMinimumSize(new java.awt.Dimension(132, 28));
        btnAgregarUser.setPreferredSize(new java.awt.Dimension(132, 28));
        btnAgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUserActionPerformed(evt);
            }
        });

        tablaUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        tablaUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.setIntercellSpacing(new java.awt.Dimension(2, 2));
        tablaUsuarios.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tablaUsuarios.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaUsuarios.setShowGrid(true);
        jScrollPane1.setViewportView(tablaUsuarios);

        btnRemoverUsuario.setBackground(new java.awt.Color(51, 51, 51));
        btnRemoverUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRemoverUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoverUsuario.setText("Remover usuario");
        btnRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnAgregarUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tab1.addTab("Usuarios", panelUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1))
        );

        tab1.getAccessibleContext().setAccessibleName("usuarios");
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUsuarioActionPerformed
        // TODO add your handling code here:
        if(btnRemoverUsuario.isVisible()){
            if (gestor.gestionarUsuarios(TipoAccion.ELIMINAR, usuarioSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente");
                eliminarUsuario();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el usuario");
            }
        }

    }//GEN-LAST:event_btnRemoverUsuarioActionPerformed

    private void btnAgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUserActionPerformed
        // TODO add your handling code here:
        PanelRegistro.setUpLabels(PanelRegistro.REGISTRAR_USUARIO);
        ((Frame) SwingUtilities.getWindowAncestor(PanelDashboard.this)).mostrarVentana("PanelRegistro");
    }//GEN-LAST:event_btnAgregarUserActionPerformed

    private void btnRegistrarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPrestamoActionPerformed
        // TODO add your handling code here:
        PanelRegistro.setUpLabels(PanelRegistro.REGISTRAR_PRESTAMO);
        ((Frame) SwingUtilities.getWindowAncestor(PanelDashboard.this)).mostrarVentana("PanelRegistro");
    }//GEN-LAST:event_btnRegistrarPrestamoActionPerformed

    private void btnRemoverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverLibroActionPerformed
        // TODO add your handling code here:
        if(btnRemoverLibro.isVisible()){
            if (gestor.gestionarLibros(TipoAccion.ELIMINAR, libroSeleccionado)) {
                JOptionPane.showMessageDialog(this, "Libro eliminado exitosamente");
                eliminarLibro();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el libro");
            }
        }
    }//GEN-LAST:event_btnRemoverLibroActionPerformed

    private void btnAggLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggLibroActionPerformed
        // TODO add your handling code here:
        PanelRegistro.setUpLabels(PanelRegistro.REGISTRAR_LIBRO);
        ((Frame) SwingUtilities.getWindowAncestor(PanelDashboard.this)).mostrarVentana("PanelRegistro");
    }//GEN-LAST:event_btnAggLibroActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarLibro();
        if(libros != null &&!libros.isEmpty()){
            mostrarLibros();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevActionPerformed
        // TODO add your handling code here:
        devolverLibro();
    }//GEN-LAST:event_btnDevActionPerformed

    protected void devolverLibro(){
        DevolucionDTO devolucion = new DevolucionDTO();
        devolucion.setIsbnLibro(prestamoSeleccionado.getIsbnLibro());
        boolean flag = gestor.registrarDevolucion(devolucion);
        if(flag){
            JOptionPane.showMessageDialog(this, "Devolucion registrada exitosamente");
            int index = prestamos.indexOf(prestamoSeleccionado);
            modeloTablaPrestamos.setValueAt(convertirFecha(Calendar.getInstance()), index, 4);
            buscarLibros();
            mostrarLibros();
        }
    }
    
    private void eliminarLibro(){
        int index = libros.indexOf(libroSeleccionado);
        libros.remove(index);
        modeloTablaLibros.removeRow(index);
    }
    
    private void eliminarUsuario(){
        int index = usuarios.indexOf(usuarioSeleccionado);
        usuarios.remove(index);
        modeloTablaUsuarios.removeRow(index);
    }
    
    protected static void agregarLibro(LibroDTO libro){
        libros.add(libro);
        String titulo = libro.getTitulo();
        String autor = libro.getAutor();
        String isbn = libro.getIsbn();
        String[] data = {titulo,autor,isbn};
        modeloTablaLibros.addRow(data);
    }
    
    protected static void agregarUsuario(UsuarioDTO usuario){
        usuarios.add(usuario);
        String email = usuario.getEmail();
        String nombre = usuario.getNombre();
        String id = String.valueOf(modeloTablaUsuarios.getRowCount()+1);
        String[] data = {id,nombre,email};
        modeloTablaUsuarios.addRow(data);
    }
    
    protected static void agregarPrestamo(PrestamoDTO prestamo){
        prestamos.add(prestamo);
        String email = prestamo.getEmailUsuario();
        String nombre = prestamo.getIsbnLibro();
        String fechaRegistro = convertirFecha(prestamo.getFechaRegistro());
        String fechaLimite= convertirFecha(prestamo.getFechaLimite());
        String[] data = {email,nombre,fechaRegistro, fechaLimite};
        modeloTablaUsuarios.addRow(data);
    }
    
    private void buscarLibros(){
        List<LibroDTO> dtos = gestor.buscarLibros();
        if(dtos!= null && !dtos.isEmpty()){
            libros = dtos;
        }
    }
    
    private void buscarPrestamos(){
        List<PrestamoDTO> dtos = gestor.buscarPrestamos();
        if(dtos != null && !dtos.isEmpty()){
            prestamos = dtos;
        }
    }
    
    private void buscarLibro(){
        LibroDTO libroBuscado = new LibroDTO();
        String busqueda = txtBusqueda.getText();
        TipoBusqueda criterio;
        if(!busqueda.isBlank()){
            int index = filtros.getSelectedIndex();
            switch (index) {
                case 0 -> {
                    libroBuscado.setTitulo(busqueda);
                    criterio = TipoBusqueda.TITULO;
                }
                case 1 -> {
                    libroBuscado.setAutor(busqueda);
                    criterio = TipoBusqueda.AUTOR;
                }
                default -> {
                    libroBuscado.setIsbn(busqueda);
                    criterio = TipoBusqueda.ISBN;
                }
            }
            libros = gestor.busquedaLibro(criterio, libroBuscado);
        }
    }
    
    private void obtenerUsuarios(){
        List<UsuarioDTO> users = gestor.buscarUsuarios();
        System.out.println("users: "+users);
        if(users != null && !users.isEmpty())
            usuarios = users;
        else System.out.println("users null");
    }
    
    private void mostrarUsuarios(){
        obtenerUsuarios();
        if(usuarios != null){
            String[][] data = new String[usuarios.size()][3];
            String[] columnNames = {"Id", "Nombre", "Email"};
            int fila = 0;
            for (UsuarioDTO usuario : usuarios) {
                System.out.println("usuario: "+usuario);
                data[fila][0] = usuario.getId();
                data[fila][1] = usuario.getNombre();
                data[fila][2] = usuario.getEmail();
                fila++;
            }
            modeloTablaUsuarios = new DefaultTableModel(data, columnNames);
            tablaUsuarios.getSelectionModel().addListSelectionListener(event -> listenerRowSelectionUsuarios(event));
            tablaUsuarios.setModel(modeloTablaUsuarios);
        }
    }
    
    private void listenerRowSelectionPrestamo(ListSelectionEvent event){
        if (!event.getValueIsAdjusting()) {
            int filaSeleccionada = tablaPrestamos.getSelectedRow();

            if (filaSeleccionada != -1) {
                prestamoSeleccionado = prestamos.get(filaSeleccionada);
                System.out.println("prestamo seleccionado: "+prestamoSeleccionado);
                
                btnDev.setVisible(true);
            }else
                btnDev.setVisible(false);
        }
    }
    
    private void listenerRowSelectionLibros(ListSelectionEvent event){
        if (!event.getValueIsAdjusting()) {
            int filaSeleccionada = tablaLibros.getSelectedRow();

            if (filaSeleccionada != -1) {
                libroSeleccionado = libros.get(filaSeleccionada);
                System.out.println("libro seleccionado: "+libroSeleccionado);
                
                btnRemoverLibro.setVisible(true);
            }else
                btnRemoverLibro.setVisible(false);
        }
    }
    
    private void listenerRowSelectionUsuarios(ListSelectionEvent event){
        if (!event.getValueIsAdjusting()) {
            int filaSeleccionada = tablaUsuarios.getSelectedRow();

            if (filaSeleccionada != -1) {
                usuarioSeleccionado = usuarios.get(filaSeleccionada);
                System.out.println("user seleccioado: "+usuarioSeleccionado.getEmail());
                
                btnRemoverUsuario.setVisible(true);
            }else
                btnRemoverUsuario.setVisible(false);
        }
    }
    
    private void mostrarLibros(){
        String[][] data = new String[libros.size()][4];
        String [] columnNames = {"Titulo", "Autor", "ISBN","Disponibilidad"};
        int fila = 0;
        for (LibroDTO libro : libros) {
            data[fila][0] = libro.getTitulo();
            data[fila][1] = libro.getAutor();
            data[fila][2] = libro.getIsbn();
            if(libro.isDisponible())
                data[fila][3] = "disponible";
            else
                data[fila][3] = "no disponible";
            fila++;
        }
        modeloTablaLibros = new DefaultTableModel(data, columnNames);
        tablaLibros.getSelectionModel().addListSelectionListener(event -> listenerRowSelectionLibros(event));
        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    }
    
    public static String convertirFecha(Calendar fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        return formato.format(fecha.getTime());
    }
    
    private void mostrarPrestamos(){
        String[][] data = new String[prestamos.size()][5];
        String [] columnNames = { "Usuario", "Libro","Fecha Prestamo","Fecha limite", "Fecha devolucion"};
        int fila = 0;
        System.out.println("prestamos: "+prestamos);
        for (PrestamoDTO prestamo : prestamos) {
            data[fila][0] = prestamo.getEmailUsuario();
            data[fila][1] = prestamo.getIsbnLibro();
            data[fila][2] = convertirFecha(prestamo.getFechaRegistro());
            data[fila][3] = convertirFecha(prestamo.getFechaLimite());
            if(prestamo.getFechaDevolucion()!= null)
                data[fila][4] = convertirFecha(prestamo.getFechaDevolucion());
            fila++;
        }
        modeloTablaPrestamos = new DefaultTableModel(data, columnNames);
        tablaPrestamos.getSelectionModel().addListSelectionListener(event -> listenerRowSelectionPrestamo(event));
        tablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggLibro;
    private javax.swing.JButton btnAgregarUser;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDev;
    private javax.swing.JButton btnRegistrarPrestamo;
    private javax.swing.JButton btnRemoverLibro;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JComboBox<String> filtros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelLibros;
    private javax.swing.JPanel panelPrestamos;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JTabbedPane tab1;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTable tablaPrestamos;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
